MVC/SportsStore/SportsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

MVC/SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get
            {
                return (int) Math.Ceiling((decimal) TotalItems/ItemsPerPage);
            }
        }
    }
}

MVC/SportsStore/SportsStore.WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

MVC/SportsStore/SportsStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;

        public CartController(IProductRepository repo)
        {
            repository = repo;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index",new {returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if(product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });

        }
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart) Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}

MVC/SportsStore/SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

MVC/SportsStore/SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Sports Store: Your Cart";
}

<h2>Your cart</h2>
<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th>Price</th>
        <th>Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.Cart.Lines)
    {
        <tr>
            <td>@line.Quantity</td>
            <td>@line.Product.Name</td>
            <td>@line.Product.Price.ToString("c")</td>
            <td>@((line.Quantity*line.Product.Price).ToString("c"))</td>
            <td>@using (Html.BeginForm("RemovefromCart", "Cart")) {
                @Html.Hidden("ProductId",line.Product.ProductID)
                @Html.HiddenFor(x=>x.ReturnUrl)
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-minus-sign"></span></button>
            }
            </td >
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td>Total:</td>
        <td>@Model.Cart.ComputeTotalValue().ToString("c")</td>
    </tr>
    </tfoot>
</table>
<div>
    <a href="@Model.ReturnUrl" class="btn btn-info">Continue shopping</a>
    
    <a href="@Url.Action("Checkout")" class="btn btn-primary">Checkout Now 
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

MVC/SportsStore/SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>


<div class="list-group">
    
    @Html.RouteLink("Home", new {controller = "Product", action = "List", page=1}, htmlAttributes: new {@class="list-group-item"})

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new {controller = "Product", action = "List", category = link, page = 1}, htmlAttributes: new {@class = link ==ViewBag.SelectedCategory? "list-group-item active" : "list-group-item" })
    }
</div>

MVC/SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    Html.RenderPartial("ProductSummary",p);
}

@Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new {page = x,category=Model.CurrentCategory}))

MVC/SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <h3>@Model.Name</h3>
        </div>
    </div>
    <div class="panel-body">
        @Model.Description
    </div>
    <div class="panel-footer">
        <p>@Model.Price.ToString("c")</p>

        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.HiddenFor(x=>x.ProductID)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)

            <button type="submit" class="btn btn-success">
                Add to cart <span class="glyphicon glyphicon-shopping-cart"></span>
            </button>
        }
    </div>
</div>

MVC/SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SportsStore</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sports Store", "List", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{ Html.RenderAction("Summary", "Cart");}
                </ul>
            </div>
        </div>
    </div>
<div class="container">
    <div class="row-fluid">
        <div id="categories" class="col-md-2">
            @{Html.RenderAction("Menu","Nav");}
        </div>
        <div class="col-md-10 body-content">
            @RenderBody()
            <hr/>
        </div>
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - www.fabsmiths.com</p>
    </footer>
</div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>